language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codeclimate-test-reporter
# command to run tests

#test coverage should appear in coverall
script:
  - pytest --cov-report term-missing --cov=app/tests/v1/test_application.py

after_success:
  - coveralls
  - codeclimate-test-reporter
