language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install code-climate-test-reporter
# command to run tests

#test coverage should appear in coverall
script:
  - pytest app/tests/v1/test_application.py
  - coveralls

after_success:
  - coveralls
  - code-climate-test-reporter
