language: python
python:
  - "2.7"

# install dependencies
install:
  - pip install -r requirements.txt
# command to run tests

# run pytest and coveralls script
script:
  - pytest --cov-report term-missing --cov=app/

# then post the results to coveralls
after_success:
  - coveralls
