language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests

#test coverage should appear in coverall
script:
  - pytest app/tests/v1/test_application.py  --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing

after_success:
  - coveralls
